<meta name="csrf-token" content="<?= csrf_hash() ?>">

<input type="hidden" id="campus_id" name="campus_id" value="<?= session('member_campusid') ?>">
<?= form_open_multipart(base_url('admin/students/save_admission'), ['id' => 'student-admission-form', 'class' => 'needs-validation']) ?>
<?= csrf_field() ?>

<div class="container-fluid px-3">
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex justify-content-between align-items-center bg-primary text-white">
            <h5 class="mb-0"><i class="fas fa-user-graduate me-2"></i> Student Admission Registration</h5>
            <button type="button" class="btn btn-light btn-sm" onclick="window.print();">
                <i class="fas fa-print"></i> Print / Save PDF
            </button>
        </div>
        <div class="card-body">
            <?php if (session()->getFlashdata('success')): ?>
                <div class="alert alert-success">
                    <i class="fas fa-check-circle me-2"></i><?= session()->getFlashdata('success') ?>
                </div>
            <?php endif; ?>

            <div class="alert alert-info d-flex align-items-center">
                <i class="fas fa-info-circle me-3 fs-4"></i>
                <div>
                    <strong>Admission Guidelines</strong>
                    <ul class="mb-0">
                        <li>All fields marked with <span class="text-danger">*</span> are mandatory</li>
                        <li>Provide accurate information to avoid processing delays</li>
                        <li>Upload clear scanned copies of required documents</li>
                    </ul>
                </div>
            </div>

            <div id="admissionAccordion" class="accordion">
                <!-- Student Information Section -->
                <div class="card mb-3 border-primary">
                    <div class="card-header bg-light-primary" id="headingStudent">
                        <h6 class="mb-0">
                            <button class="accordion-button fw-bold text-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseStudent" aria-expanded="true">
                                <i class="fas fa-user-graduate me-2"></i> Student Personal Details
                            </button>
                        </h6>
                    </div>
                    <div id="collapseStudent" class="collapse show" aria-labelledby="headingStudent" data-bs-parent="#admissionAccordion">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4 mb-3">
                                    <label for="first_name" class="form-label required">
                                        <i class="fas fa-signature me-1"></i> Full Name
                                    </label>
                                    <input type="text" required class="form-control form-control-sm" name="first_name" id="first_name" value="<?= esc($first_name) ?>">
                                    <small class="form-text text-muted">As per birth certificate</small>
                                </div>

                                <div class="col-md-4 mb-3">
                                    <label for="reg_no" class="form-label">
                                        <i class="fas fa-id-badge me-1"></i> Registration No.
                                    </label>
                                    <input type="text" class="form-control form-control-sm" name="reg_no" id="reg_no" value="<?= esc($reg_no) ?>" readonly>
                                    <small class="form-text text-muted">Auto-generated by system</small>
                                </div>

                                <div class="col-md-4 mb-3">
                                    <label for="gr_no" class="form-label">
                                        <i class="fas fa-hashtag me-1"></i> G.R. Number
                                    </label>
                                    <input type="text" class="form-control form-control-sm" name="gr_no" id="gr_no" value="<?= esc($gr_no ?? '') ?>">
                                    <small class="form-text text-muted">General Register number</small>
                                </div>

                                <div class="col-md-4 mb-3">
                                    <label for="gr_date" class="form-label">
                                        <i class="far fa-calendar-alt me-1"></i> G.R. Date
                                    </label>
                                    <div class="input-group">
                                        <span class="input-group-text"><i class="far fa-calendar"></i></span>
                                        <input type="text" class="form-control form-control-sm datepicker" name="gr_date" id="gr_date" 
                                               value="<?= esc($gr_date ?? date('d/m/Y')) ?>" placeholder="dd/mm/yyyy" readonly>
                                    </div>
                                    <small class="form-text text-muted">Date of registration</small>
                                </div>

                                <div class="col-md-4 mb-3">
                                    <label for="date_of_admission" class="form-label required">
                                        <i class="fas fa-calendar-check me-1"></i> Admission Date
                                    </label>
                                    <div class="input-group">
                                        <span class="input-group-text"><i class="far fa-calendar"></i></span>
                                        <input type="text" required class="form-control form-control-sm datepicker" name="date_of_admission" 
                                               id="date_of_admission" value="<?= esc($date_of_admission ?? date('d/m/Y')) ?>" 
                                               placeholder="dd/mm/yyyy" readonly>
                                    </div>
                                    <small class="form-text text-muted">Official admission date</small>
                                </div>

                                <div class="col-md-4 mb-3">
                                    <label for="date_of_birth" class="form-label required">
                                        <i class="fas fa-birthday-cake me-1"></i> Date of Birth
                                    </label>
                                    <div class="input-group">
                                        <span class="input-group-text"><i class="far fa-calendar"></i></span>
                                        <input type="text" required class="form-control form-control-sm datepicker" name="date_of_birth" id="date_of_birth" value="<?= esc($date_of_birth ?? '') ?>" placeholder="dd/mm/yyyy" readonly>
                                    </div>
                                    <div id="age-badge" class="mt-2"></div>
                                    <small class="form-text text-muted">As per birth certificate</small>
                                </div>

                                <div class="col-md-4 mb-3">
                                    <label for="gender" class="form-label required">
                                        <i class="fas fa-venus-mars me-1"></i> Gender
                                    </label>
                                    <select class="form-control form-control-sm" name="gender" id="gender" required>
                                        <option value="">Select Gender</option>
                                        <option value="male" <?= ($gender ?? '') == 'male' ? 'selected' : '' ?>>Male</option>
                                        <option value="female" <?= ($gender ?? '') == 'female' ? 'selected' : '' ?>>Female</option>
                                        <option value="other" <?= ($gender ?? '') == 'other' ? 'selected' : '' ?>>Other</option>
                                    </select>
                                </div>

                                <div class="col-md-4 mb-3">
                                    <label for="student_cnic" class="form-label">
                                        <i class="fas fa-id-card me-1"></i> Student CNIC/B-Form
                                    </label>
                                    <input type="text" class="form-control form-control-sm cnic-mask" name="student_cnic" id="student_cnic" value="<?= esc($student_cnic) ?>" placeholder="XXXXX-XXXXXXX-X">
                                    <small class="form-text text-muted">Format: 12345-1234567-1</small>
                                </div>

                                <div class="col-md-4 mb-3">
                                    <label for="previous_school" class="form-label">
                                        <i class="fas fa-school me-1"></i> Previous School
                                    </label>
                                    <input type="text" class="form-control form-control-sm" name="previous_school" value="<?= esc($previous_school ?? '') ?>">
                                    <small class="form-text text-muted">If applicable</small>
                                </div>

                                <div class="col-md-4 mb-3">
                                    <label for="ps_city" class="form-label">
                                        <i class="fas fa-city me-1"></i> Previous School City
                                    </label>
                                    <input type="text" class="form-control form-control-sm" name="ps_city" value="<?= esc($ps_city ?? '') ?>">
                                </div>

                                <div class="col-md-6 mb-3">
                                    <label for="health_conditions" class="form-label">
                                        <i class="fas fa-heartbeat me-1"></i> Health Conditions
                                    </label>
                                    <textarea class="form-control" name="health_conditions" rows="2" placeholder="Any known medical conditions or allergies"><?= esc($health_conditions ?? '') ?></textarea>
                                    <small class="form-text text-muted">Important for emergency situations</small>
                                </div>

                                <div class="col-md-6 mb-3">
                                    <label for="major_injuries" class="form-label">
                                        <i class="fas fa-procedures me-1"></i> Major Injuries/Illnesses
                                    </label>
                                    <textarea class="form-control" name="major_injuries" rows="2" placeholder="Any significant past medical history"><?= esc($major_injuries ?? '') ?></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Fee Structure Section -->
                <div class="card mb-3 border-success">
                    <div class="card-header bg-light-success" id="headingFee">
                        <h6 class="mb-0">
                            <button class="accordion-button fw-bold text-success collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFee">
                                <i class="fas fa-money-bill-wave me-2"></i> Fee Structure & Financial Details
                            </button>
                        </h6>
                    </div>
                    <div id="collapseFee" class="collapse" aria-labelledby="headingFee" data-bs-parent="#admissionAccordion">
                        <div class="card-body">
                            <div class="alert alert-warning">
                                <i class="fas fa-exclamation-triangle me-2"></i>
                                <strong>Important:</strong> Fee structure will be locked after submission. Any changes will require administrative approval.
                            </div>

                            <div class="row mb-4">
                                <div class="col-md-4 mb-3">
                                    <label for="section_id" class="form-label required">
                                        <i class="fas fa-chalkboard me-1"></i> Class Section
                                    </label>
                                    <select class="form-control form-control-sm" name="section_id" id="section_id" required>
                                        <option value="">Select Class Section</option>
                                        <?php foreach ($sectionsclassinfo as $sectionvalue): ?>
                                            <option value="<?= $sectionvalue['section_id'] ?>" <?= ($sectionvalue['section_id'] == ($section_id ?? 0)) ? 'selected' : '' ?>>
                                                <?= esc($sectionvalue['sectionclassname']) ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                    <small class="form-text text-muted">Determines applicable fees</small>
                                </div>
                                
                                <div class="col-md-4 mb-3">
                                    <label for="fee_issue_date" class="form-label required">
                                        <i class="fas fa-calendar-day me-1"></i> Fee Issue Date
                                    </label>
                                    <div class="input-group">
                                        <span class="input-group-text"><i class="far fa-calendar"></i></span>
                                        <input type="text" required class="form-control form-control-sm datepicker" name="fee_issue_date" id="fee_issue_date" placeholder="dd/mm/yyyy" readonly>
                                    </div>
                                </div>
                                
                                <div class="col-md-4 mb-3">
                                    <label for="fee_due_date" class="form-label required">
                                        <i class="fas fa-clock me-1"></i> Fee Due Date
                                    </label>
                                    <div class="input-group">
                                        <span class="input-group-text"><i class="far fa-calendar"></i></span>
                                        <input type="text" required class="form-control form-control-sm datepicker" name="fee_due_date" id="fee_due_date" placeholder="dd/mm/yyyy" readonly>
                                    </div>
                                    <small class="form-text text-muted">Payment deadline</small>
                                </div>
                                
                                <div class="col-md-4 mb-3">
                                    <label for="fee_month" class="form-label required">
                                        <i class="fas fa-calendar-alt me-1"></i> Fee Month
                                    </label>
                                    <input type="month" required class="form-control form-control-sm" name="fee_month" id="fee_month">
                                    <small class="form-text text-muted">For which month fees apply</small>
                                </div>
                                
                                <div class="col-md-4 mb-3">
                                    <label class="form-label">
                                        <i class="fas fa-file-invoice me-1"></i> Invoice Number
                                    </label>
                                    <input type="text" class="form-control form-control-sm" id="invoice_number_preview" readonly>
                                    <input type="hidden" name="invoice_number" id="invoice_number">
                                    <small class="form-text text-muted">Auto-generated invoice reference</small>
                                </div>
                            </div>
                            
                            <div class="table-responsive">
                                <table class="table table-sm table-bordered">
                                    <thead class="table-light">
                                        <tr>
                                            <th><i class="fas fa-list me-1"></i> Fee Type</th>
                                            <th width="20%"><i class="fas fa-money-bill me-1"></i> Standard Amount</th>
                                            <th width="20%"><i class="fas fa-hand-holding-usd me-1"></i> Payable Amount</th>
                                            <th width="20%"><i class="fas fa-tag me-1"></i> Discount/Adjustment</th>
                                        </tr>
                                    </thead>
                                    <tbody id="fee-type-container">
                                        <tr>
                                            <td colspan="4" class="text-center py-4 text-muted">
                                                <i class="fas fa-info-circle me-2"></i>Select class section to load fee structure
                                            </td>
                                        </tr>
                                    </tbody>
                                    <tfoot class="table-group-divider">
                                        <tr class="table-active">
                                            <th class="text-end"><i class="fas fa-calculator me-1"></i> Total</th>
                                            <th id="total-default">0.00</th>
                                            <th id="total-student">0.00</th>
                                            <th id="total-discount">0.00</th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                            
                            <div class="alert alert-info mt-3">
                                <i class="fas fa-question-circle me-2"></i>
                                <strong>Need help?</strong> Contact accounts department for fee structure queries or discount approvals.
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Parent Information Section -->
                <div class="card mb-3 border-info">
                    <div class="card-header bg-light-info" id="headingParent">
                        <h6 class="mb-0">
                            <button class="accordion-button fw-bold text-info collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseParent">
                                <i class="fas fa-users me-2"></i> Parent/Guardian Information
                            </button>
                        </h6>
                    </div>
                  
                    <div id="collapseParent" class="collapse" aria-labelledby="headingParent" data-bs-parent="#admissionAccordion">
                        <div class="card-body">
                            <div class="alert alert-primary">
                                <i class="fas fa-lightbulb me-2"></i>
                                <strong>Pro Tip:</strong> We'll automatically retrieve parent information if they're already in our system.
                                Just enter the Father's CNIC to check.
                            </div>
                            
                            <div class="row">
                                <input type="hidden" id="parent_id" name="parent_id" value="">
                                
                                <div class="col-md-12 mb-3">
                                    <div class="form-check form-switch">
                                        <input class="form-check-input" type="checkbox" id="edit_parent_info" role="switch">
                                        <label class="form-check-label" for="edit_parent_info">
                                            <i class="fas fa-edit me-1"></i> Edit Parent Information
                                        </label>
                                        <small class="form-text d-block text-muted">Enable to modify parent details</small>
                                    </div>
                                </div>

                                <div class="col-md-4 mb-3">
                                    <label for="father_cnic" class="form-label required">
                                        <i class="fas fa-id-card me-1"></i> Father's CNIC
                                    </label>
                                    <div class="input-group">
                                        <span class="input-group-text"><i class="fas fa-id-card"></i></span>
                                        <input type="text" required class="form-control form-control-sm cnic-mask parent-field" name="father_cnic" id="father_cnic" value="<?= esc($father_cnic) ?>" placeholder="XXXXX-XXXXXXX-X" disabled>
                                        <span id="cnic-spinner" class="input-group-text d-none">
                                            <i class="fas fa-spinner fa-spin"></i>
                                        </span>
                                    </div>
                                    <small class="form-text text-muted">Required for verification</small>
                                    <div id="children-info-container" class="mt-2"></div>
                                </div>

                                <?php
                                $fields = [
                                    ['f_name', 'Father\'s Full Name', $f_name ?? '', true],
                                    ['father_contact', 'Father\'s Contact', $father_contact ?? ''],
                                    ['father_email', 'Father\'s Email', $father_email ?? ''],
                                    ['father_occupation', 'Father\'s Occupation', $father_occupation ?? ''],
                                    ['father_office_address', 'Father\'s Office Address', $father_office_address ?? ''],
                                    ['m_name', 'Mother\'s Full Name', $m_name ?? ''],
                                    ['mother_contact', 'Mother\'s Contact', $mother_contact ?? ''],
                                    ['whatsapp_contact', 'WhatsApp Number', $whatsapp_contact ?? ''],
                                    ['address_line1', 'Residential Address', $address_line1 ?? ''],
                                    ['city', 'City', $city ?? ''],
                                    ['hear_source', 'How did you hear about us?', $hear_source ?? ''],
                                    ['emergency_contact_person', 'Emergency Contact Person', $emergency_contact_person ?? ''],
                                    ['emergency_contact', 'Emergency Contact Number', $emergency_contact ?? ''],
                                    ['a_address', 'Emergency Contact Address', $a_address ?? ''],
                                ];

                                foreach ($fields as $field) {
                                    [$name, $label, $value, $required] = array_pad($field, 4, false);
                                    $icon = '';
                                    $placeholder = '';
                                    
                                    // Set appropriate icons and placeholders
                                    switch($name) {
                                        case 'f_name':
                                        case 'm_name':
                                            $icon = 'fas fa-user';
                                            break;
                                        case 'father_contact':
                                        case 'mother_contact':
                                        case 'emergency_contact':
                                            $icon = 'fas fa-phone';
                                            $placeholder = '+92 XXX XXXXXXX';
                                            break;
                                        case 'father_email':
                                            $icon = 'fas fa-envelope';
                                            $placeholder = 'example@domain.com';
                                            break;
                                        case 'father_occupation':
                                            $icon = 'fas fa-briefcase';
                                            break;
                                        case 'address_line1':
                                        case 'a_address':
                                        case 'father_office_address':
                                            $icon = 'fas fa-map-marker-alt';
                                            break;
                                        case 'city':
                                            $icon = 'fas fa-city';
                                            break;
                                        case 'hear_source':
                                            $icon = 'fas fa-bullhorn';
                                            break;
                                        case 'whatsapp_contact':
                                            $icon = 'fab fa-whatsapp';
                                            $placeholder = '+92 XXX XXXXXXX';
                                            break;
                                        default:
                                            $icon = 'fas fa-info-circle';
                                    }
                                ?>
                                <div class="col-md-4 mb-3">
                                    <label for="<?= $name ?>" class="form-label <?= $required ? 'required' : '' ?>">
                                        <i class="<?= $icon ?> me-1"></i> <?= $label ?>
                                    </label>
                                    <?php if(in_array($name, ['father_contact', 'mother_contact', 'emergency_contact', 'whatsapp_contact'])): ?>
                                        <div class="input-group">
                                            <span class="input-group-text"><i class="<?= $icon ?>"></i></span>
                                            <input type="text" class="form-control form-control-sm phone-mask parent-field" name="<?= $name ?>" id="<?= $name ?>" 
                                                   value="<?= esc($value) ?>" <?= $required ? 'required' : '' ?> 
                                                   placeholder="<?= $placeholder ?>" disabled>
                                        </div>
                                    <?php else: ?>
                                        <input type="text" class="form-control form-control-sm parent-field" name="<?= $name ?>" id="<?= $name ?>" 
                                               value="<?= esc($value) ?>" <?= $required ? 'required' : '' ?> 
                                               placeholder="<?= $placeholder ?>" disabled>
                                    <?php endif; ?>
                                </div>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Documents Section -->
                <div class="card border-warning">
                    <div class="card-header bg-light-warning" id="headingAttachments">
                        <h6 class="mb-0">
                            <button class="accordion-button fw-bold text-warning collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseAttachments">
                                <i class="fas fa-file-upload me-2"></i> Required Documents
                            </button>
                        </h6>
                    </div>
                    <div id="collapseAttachments" class="collapse" aria-labelledby="headingAttachments" data-bs-parent="#admissionAccordion">
                        <div class="card-body">
                            <div class="alert alert-warning">
                                <div class="d-flex">
                                    <i class="fas fa-exclamation-triangle me-3 fs-4"></i>
                                    <div>
                                        <strong>Document Requirements</strong>
                                        <ul class="mb-0">
                                            <li>All documents must be clear, color scans (max 2MB each)</li>
                                            <li>Accepted formats: JPG, PNG, PDF</li>
                                            <li>Ensure documents are valid and not expired</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row">
                                <?php
                                $db = \Config\Database::connect();
                                foreach ($attachementTypesInfo as $value):
                                    $attachement = $db->table('attachements')
                                        ->where('student_id', $id ?? 0)
                                        ->where('a_type_id', $value->a_type_id)
                                        ->get()
                                        ->getRow();
                                ?>
                                <div class="col-md-6 col-lg-4 mb-4">
                                    <div class="card h-100 border-0 shadow-sm">
                                        <div class="card-header bg-light">
                                            <h6 class="card-title mb-0 text-primary">
                                                <i class="fas fa-file me-2"></i><?= esc($value->a_type_name) ?>
                                            </h6>
                                        </div>
                                        <div class="card-body text-center">
                                            <input type="hidden" class="a_type_id" value="<?= $value->a_type_id ?>">
                                            <input type="hidden" class="attachement_id" value="<?= $attachement->attachement_id ?? 0 ?>">
                                            
                                            <div class="document-preview-container mb-3">
                                                <img id="preview_<?= $value->a_type_id ?>" 
                                                    src="<?= $attachement ? base_url('studentattachements/' . $attachement->attachement_path) : 'https://via.placeholder.com/300x200?text=Upload+Document' ?>"
                                                    class="attachment-preview img-thumbnail">
                                            </div>
                                            
                                            <div class="d-grid gap-2">
                                                <input type="file" class="form-control d-none attachment-file" data-typeid="<?= $value->a_type_id ?>" id="attachment_<?= $value->a_type_id ?>" accept="image/*,.pdf">
                                                <button class="btn btn-sm btn-outline-primary" onclick="document.getElementById('attachment_<?= $value->a_type_id ?>').click()">
                                                    <i class="fas fa-upload me-2"></i>Upload Document
                                                </button>
                                                
                                                <?php if ($attachement): ?>
                                                    <a href="<?= base_url('studentattachements/' . $attachement->attachement_path) ?>" target="_blank" class="btn btn-sm btn-outline-success">
                                                        <i class="fas fa-eye me-2"></i>View Document
                                                    </a>
                                                    <button class="btn btn-sm btn-outline-danger remove-document" data-typeid="<?= $value->a_type_id ?>">
                                                        <i class="fas fa-trash me-2"></i>Remove
                                                    </button>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                        <div class="card-footer bg-light">
                                            <small class="text-muted">
                                                <i class="fas fa-info-circle me-1"></i>
                                                <?= $value->description ?? 'Required for admission processing' ?>
                                            </small>
                                        </div>
                                    </div>
                                </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Form Submission Section -->
            <div class="card mt-4 border-secondary">
                <div class="card-body text-center">
                    <div class="alert alert-secondary mb-4">
                        <i class="fas fa-clipboard-check me-2"></i>
                        <strong>Before submitting:</strong> Please verify all information is accurate. Changes after submission may require administrative approval.
                    </div>
                    
                    <div class="d-flex justify-content-center">
                        <button type="submit" class="btn btn-success px-4 py-2 me-3">
                            <i class="fas fa-save me-2"></i>Submit Admission
                        </button>
                        <button type="reset" class="btn btn-outline-secondary px-4 py-2 me-3">
                            <i class="fas fa-undo me-2"></i>Reset Form
                        </button>
                        <a href="<?= base_url('admin/students') ?>" class="btn btn-outline-danger px-4 py-2">
                            <i class="fas fa-times me-2"></i>Cancel
                        </a>
                    </div>
                    
                    <div class="mt-3 text-muted">
                        <small>
                            <i class="fas fa-lock me-1"></i> Your information is secure and protected
                        </small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?= form_close() ?>

<!-- Include necessary JS libraries -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/inputmask/4.0.9/jquery.inputmask.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">

<!-- Custom Styles -->
<style>
.required:after {
    content: " *";
    color: #dc3545;
}

.accordion-button {
    font-weight: 500;
}

.attachment-preview {
    max-height: 200px;
    object-fit: contain;
    border: 1px solid #dee2e6;
    background: #f8f9fa;
}

.document-preview-container {
    height: 180px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: #f8f9fa;
    border-radius: 4px;
    overflow: hidden;
}

.badge-custom {
    padding: 0.5em 0.75em;
    font-size: 0.85em;
}

.children-info {
    border-start: 3px solid #0dcaf0;
    font-size: 0.85rem;
    padding: 0.75rem;
    background-color: #f8f9fa;
}

.children-list {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
    margin-top: 0.5rem;
}

.child-badge {
    font-size: 0.75rem;
    font-weight: normal;
    white-space: nowrap;
    padding: 0.35em 0.65em;
}

.bg-light-primary {
    background-color: #e7f5ff;
}

.bg-light-success {
    background-color: #ebfbee;
}

.bg-light-info {
    background-color: #e7f5ff;
}

.bg-light-warning {
    background-color: #fff9db;
}

/* Responsive adjustments */
@media (max-width: 768px) {
    .document-preview-container {
        height: 150px;
    }
}
</style>

<script>
$(document).ready(function() {
    // Initialize datepickers with default values
    const today = new Date();
    const dueDate = new Date();
    dueDate.setDate(today.getDate() + 10); // 10 days from today
    
    // Format dates as dd/mm/yyyy
    const formatDate = (date) => {
        const day = String(date.getDate()).padStart(2, '0');
        const month = String(date.getMonth() + 1).padStart(2, '0');
        return `${day}/${month}/${date.getFullYear()}`;
    };

    const todayFormatted = formatDate(today);
    const dueDateFormatted = formatDate(dueDate);

    // Set default values if empty
    if (!$('#gr_date').val()) {
        $('#gr_date').val(todayFormatted);
    }
    
    if (!$('#date_of_admission').val()) {
        $('#date_of_admission').val(todayFormatted);
    }
    
    if (!$('#fee_issue_date').val()) {
        $('#fee_issue_date').val(todayFormatted);
    }
    
    if (!$('#fee_due_date').val()) {
        $('#fee_due_date').val(dueDateFormatted);
    }

    // Initialize datepickers
    $('.datepicker').datepicker({
        format: 'dd/mm/yyyy',
        autoclose: true,
        todayHighlight: true,
        endDate: new Date()
    }).attr('readonly', 'readonly');
    
    // Update datepicker with the values
    $('.datepicker').each(function() {
        $(this).datepicker('update', $(this).val());
    });
    
    // Set fee month to current month
    const month = (today.getMonth() + 1).toString().padStart(2, '0');
    $('#fee_month').val(`${today.getFullYear()}-${month}`);

    // Initialize input masks
    $('.cnic-mask').inputmask('99999-9999999-9');
    $('.phone-mask').inputmask('+99 999 9999999');

    // Document preview handler
    $('.attachment-file').on('change', function() {
        const typeId = $(this).data('typeid');
        const file = this.files[0];
        
        if (file) {
            // Validate file size (max 2MB)
            if (file.size > 2 * 1024 * 1024) {
                toastr.error('File size should not exceed 2MB');
                return;
            }
            
            // Validate file type
            const validTypes = ['image/jpeg', 'image/png', 'application/pdf'];
            if (!validTypes.includes(file.type)) {
                toastr.error('Only JPG, PNG, and PDF files are allowed');
                return;
            }
            
            const reader = new FileReader();
            reader.onload = function(e) {
                $('#preview_' + typeId).attr('src', e.target.result);
                
                // Show view and remove buttons
                $(`#attachment_${typeId}`).closest('.card-body').find('.btn-outline-success, .remove-document').removeClass('d-none');
            };
            reader.readAsDataURL(file);
        }
    });

    // Remove document handler
    $('.remove-document').on('click', function() {
        const typeId = $(this).data('typeid');
        const $preview = $('#preview_' + typeId);
        
        // Reset to placeholder
        $preview.attr('src', 'https://via.placeholder.com/300x200?text=Upload+Document');
        
        // Reset file input
        $(`#attachment_${typeId}`).val('');
        
        // Hide view and remove buttons
        $(this).closest('.card-body').find('.btn-outline-success, .remove-document').addClass('d-none');
    });

    // Age calculation and badge display
    function calculateAge(dobStr) {
        if (!dobStr) return '';
        
        const parts = dobStr.split('/');
        if (parts.length !== 3) return '';
        
        const dob = new Date(parts[2], parts[1] - 1, parts[0]);
        const today = new Date();
        
        let years = today.getFullYear() - dob.getFullYear();
        let months = today.getMonth() - dob.getMonth();
        let days = today.getDate() - dob.getDate();
        
        if (days < 0) {
            months--;
            days += new Date(today.getFullYear(), today.getMonth(), 0).getDate();
        }
        
        if (months < 0) {
            years--;
            months += 12;
        }
        
        return `${years} year${years !== 1 ? 's' : ''}, ${months} month${months !== 1 ? 's' : ''}, ${days} day${days !== 1 ? 's' : ''}`;
    }

    function updateAgeBadge() {
        const dob = $('#date_of_birth').val();
        const age = calculateAge(dob);
        
        if (age) {
            const parts = dob.split('/');
            const dobDate = new Date(parts[2], parts[1] - 1, parts[0]);
            const today = new Date();
            const ageYears = today.getFullYear() - dobDate.getFullYear();
            
            let badgeClass = 'bg-primary';
            let validityText = 'Valid age for admission';
            let validityIcon = 'fa-check-circle';
            
            if (ageYears < 3) {
                badgeClass = 'bg-warning';
                validityText = 'Too young for standard admission';
                validityIcon = 'fa-exclamation-triangle';
            } else if (ageYears > 18) {
                badgeClass = 'bg-danger';
                validityText = 'Age exceeds standard admission range';
                validityIcon = 'fa-exclamation-triangle';
            }
            
            $('#age-badge').html(`
                <div class="d-flex flex-wrap gap-2 mt-2">
                    <span class="badge ${badgeClass} text-white badge-custom">
                        <i class="fas fa-user-clock me-1"></i> Age: ${age}
                    </span>
                    <span class="badge ${ageYears >= 3 && ageYears <= 18 ? 'bg-success' : 'bg-danger'} text-white badge-custom">
                        <i class="fas ${validityIcon} me-1"></i> ${validityText}
                    </span>
                </div>
            `);
        } else {
            $('#age-badge').empty();
        }
    }
    
    // Trigger badge update on DOB change
    $('#date_of_birth').on('change', updateAgeBadge);
    updateAgeBadge();

    // Parent information handling
    function toggleParentFields(enable) {
        $('.parent-field').prop('disabled', !enable);
        if (!enable) {
            $('#edit_parent_info').prop('checked', false);
        }
    }

    // Check if parent exists by CNIC
    $('#father_cnic').on('blur', function() {
        const cnic = $(this).val();
        const campus_id = $('#campus_id').val();
        
        if (!cnic || cnic.length < 15) {
            console.log('CNIC too short');
            return;
        }
        
        if (!campus_id) {
            toastr.error('Campus information is missing');
            return;
        }
        
        $.ajax({
            url: '<?= site_url('admin/students/check_parent_cnic') ?>',
            method: 'POST',
            data: { 
                cnic: cnic,
                campus_id: campus_id,
                <?= csrf_token() ?>: '<?= csrf_hash() ?>'
            },
            dataType: 'json',
            beforeSend: function() {
                $('#cnic-spinner').removeClass('d-none');
            },
            complete: function() {
                $('#cnic-spinner').addClass('d-none');
            },
            success: function(res) {
                console.log('AJAX Success Response:', res);
                if (res.exists) {
                    // Populate parent fields
                    Object.keys(res.parent).forEach(key => {
                        const $field = $(`#${key}`);
                        if ($field.length) {
                            $field.val(res.parent[key]).trigger('change');
                        }
                    });
                    
                    // Store parent ID
                    $('#parent_id').val(res.parent.parent_id);
                    
                    // Remove any existing children container
                    $('#children-info-container').remove();
                    
                    // Create and show children information if available
                    if (res.children && res.children.length > 0) {
                        console.log('Children data:', res.children);
                        
                        let childrenHTML = `
                        <div id="children-info-container" class="mt-2">
                            <div class="children-info">
                                <small class="text-muted d-block mb-1">
                                    <i class="fas fa-child me-1"></i> Existing children in our system:
                                </small>
                                <div class="children-list">
                                    ${res.children.map(child => `
                                        <span class="child-badge badge bg-info text-dark">
                                            <i class="fas fa-user-graduate me-1"></i>
                                            ${child.name} (${child.class})
                                        </span>
                                    `).join('')}
                                </div>
                            </div>
                        </div>`;
                        
                        // Insert after the CNIC field's parent container
                        $('#father_cnic').closest('.mb-3').append(childrenHTML);
                    }
                    
                    // Disable fields and show message
                    toggleParentFields(false);
                    toastr.info('Parent information loaded from our records. Check "Edit Parent Information" to modify.');
                } else {
                    // Clear parent ID and enable fields
                    $('#parent_id').val('');
                    $('#children-info-container').remove();
                    toggleParentFields(true);
                    if (res.message) toastr.info(res.message);
                }
            },
            error: function(xhr, status, error) {
                console.error('AJAX Error:', error);
                console.log('Status:', status);
                console.log('Response:', xhr.responseText);
                
                try {
                    const response = JSON.parse(xhr.responseText);
                    toastr.error(response.error || 'Error checking parent information');
                } catch (e) {
                    toastr.error('Error checking parent information. Please try again.');
                }
            }
        });
    });

    // Toggle edit mode for parent info
    $('#edit_parent_info').change(function() {
        toggleParentFields(this.checked);
        if (this.checked) {
            toastr.info('Parent information editing enabled. Make your changes carefully.');
        }
    });

    // Enable parent fields before form submission
    $('#student-admission-form').submit(function() {
        toggleParentFields(true);
    });

    // Load fee structure when section is selected
    $('#section_id').on('change', function() {
        const cls_sec_id = $(this).val();
        if (!cls_sec_id) return;
        
        $.ajax({
            url: '<?= site_url("admin/ajax/get_class_fee_amounts") ?>',
            method: 'POST',
            data: { cls_sec_id: cls_sec_id },
            dataType: 'json',
            beforeSend: function() {
                $('#fee-type-container').html(`
                    <tr>
                        <td colspan="4" class="text-center py-4">
                            <div class="spinner-border text-primary" role="status">
                                <span class="visually-hidden">Loading...</span>
                            </div>
                            <p class="mt-2 mb-0">Loading fee structure...</p>
                        </td>
                    </tr>
                `);
            },
            success: function(res) {
                if (res.status === 'success') {
                    let html = '';
                    let totalDefault = 0;
                    let totalStudent = 0;
                    
                    res.data.forEach((fee, i) => {
                        totalDefault += parseFloat(fee.default_amount) || 0;
                        totalStudent += parseFloat(fee.default_amount) || 0;
                        
                        html += `
                            <tr class="fee-row">
                                <td>
                                    <i class="fas ${getFeeTypeIcon(fee.fee_type_title)} me-2"></i>
                                    ${fee.fee_type_title}
                                    <input type="hidden" name="fee_type_id[]" value="${fee.fee_type_id}">
                                    <small class="d-block text-muted">${fee.description || ''}</small>
                                </td>
                                <td>
                                    <div class="input-group input-group-sm">
                                        <span class="input-group-text">Rs.</span>
                                        <input type="number" class="form-control form-control-sm default-amount text-end" 
                                            value="${fee.default_amount}" readonly>
                                    </div>
                                </td>
                                <td>
                                    <div class="input-group input-group-sm">
                                        <span class="input-group-text">Rs.</span>
                                        <input type="number" name="student_amount[]" 
                                            class="form-control form-control-sm student-amount text-end" 
                                            value="${fee.default_amount}" 
                                            data-default="${fee.default_amount}">
                                    </div>
                                </td>
                                <td class="text-danger discount-info text-end">
                                    Rs. 0.00
                                </td>
                            </tr>`;
                    });
                    
                    $('#fee-type-container').html(html);
                    updateTotals();
                    
                    // Add event listeners to student amount fields
                    $('.student-amount').on('input', function() {
                        const defaultVal = parseFloat($(this).data('default')) || 0;
                        const studentVal = parseFloat($(this).val()) || 0;
                        const discount = defaultVal - studentVal;
                        
                        $(this).closest('.fee-row').find('.discount-info').html(`Rs. ${discount.toFixed(2)}`);
                        updateTotals();
                    });
                    
                    toastr.success('Fee structure loaded successfully');
                } else {
                    $('#fee-type-container').html(`
                        <tr>
                            <td colspan="4" class="text-center py-4 text-danger">
                                <i class="fas fa-exclamation-triangle me-2"></i>
                                Failed to load fee structure
                            </td>
                        </tr>
                    `);
                    toastr.error('Failed to load fee structure for selected class');
                }
            },
            error: function() {
                $('#fee-type-container').html(`
                    <tr>
                        <td colspan="4" class="text-center py-4 text-danger">
                            <i class="fas fa-exclamation-triangle me-2"></i>
                            Error loading fee structure
                        </td>
                    </tr>
                `);
                toastr.error('Error loading fee structure. Please try again.');
            }
        });
    });
    
    // Helper function to get appropriate icon for fee type
    function getFeeTypeIcon(feeType) {
        feeType = feeType.toLowerCase();
        if (feeType.includes('tuition')) return 'fa-book';
        if (feeType.includes('admission')) return 'fa-sign-in-alt';
        if (feeType.includes('exam')) return 'fa-clipboard-check';
        if (feeType.includes('transport')) return 'fa-bus';
        if (feeType.includes('activity')) return 'fa-running';
        return 'fa-money-bill-wave';
    }
    
    // Initialize with current section if selected
    <?php if (!empty($section_id)): ?>
        $('#section_id').trigger('change');
    <?php endif; ?>
    
    // Calculate totals and discounts
    function updateTotals() {
        let totalDefault = 0;
        let totalStudent = 0;
        let totalDiscount = 0;
        
        $('.fee-row').each(function() {
            const defaultVal = parseFloat($(this).find('.default-amount').val()) || 0;
            const studentVal = parseFloat($(this).find('.student-amount').val()) || 0;
            const discount = defaultVal - studentVal;
            
            totalDefault += defaultVal;
            totalStudent += studentVal;
            totalDiscount += discount;
        });
        
        $('#total-default').html(`Rs. ${totalDefault.toFixed(2)}`);
        $('#total-student').html(`Rs. ${totalStudent.toFixed(2)}`);
        $('#total-discount').html(`Rs. ${totalDiscount.toFixed(2)}`);
    }
    
    // Generate preview invoice number
    function generateInvoicePreview() {
        const today = new Date();
        const year = today.getFullYear().toString().substr(2, 2); // Last 2 digits of year
        const campusCode = '<?= session('member_campusid') ?>'.padStart(2, '0');
        
        // This is just a preview - actual number will be generated on server
        const randomSequence = Math.floor(Math.random() * 900 + 100); // Random 3-digit number
        const invoiceNo = `INV-${campusCode}-${year}${randomSequence}`;
        
        $('#invoice_number_preview').val(invoiceNo);
        $('#invoice_number').val(invoiceNo);
    }
    
    // Generate invoice preview
    generateInvoicePreview();
    
    // Form validation and submission
    $('#student-admission-form').validate({
        rules: {
            first_name: 'required',
            father_cnic: 'required',
            f_name: 'required',
            date_of_admission: 'required',
            date_of_birth: 'required',
            section_id: 'required',
            fee_issue_date: 'required',
            fee_due_date: 'required',
            fee_month: 'required',
            gender: 'required'
        },
        messages: {
            first_name: 'Student full name is required',
            father_cnic: 'Father CNIC is required for verification',
            f_name: 'Father name is required',
            date_of_admission: 'Please select admission date',
            date_of_birth: 'Please provide date of birth',
            section_id: 'Please select class section',
            fee_issue_date: 'Please select fee issue date',
            fee_due_date: 'Please select fee due date',
            fee_month: 'Please select fee month',
            gender: 'Please select gender'
        },
        errorElement: 'div',
        errorClass: 'invalid-feedback',
        highlight: function(element) {
            $(element).addClass('is-invalid').removeClass('is-valid');
            $(element).closest('.form-group').find('.input-group-text').addClass('border-danger');
        },
        unhighlight: function(element) {
            $(element).removeClass('is-invalid').addClass('is-valid');
            $(element).closest('.form-group').find('.input-group-text').removeClass('border-danger');
        },
        errorPlacement: function(error, element) {
            if (element.hasClass('datepicker')) {
                error.insertAfter(element.closest('.input-group'));
            } else if (element.hasClass('phone-mask') || element.hasClass('cnic-mask')) {
                error.insertAfter(element.closest('.input-group'));
            } else {
                error.insertAfter(element);
            }
        },
        submitHandler: function(form) {
            const formData = new FormData(form);
            
            // Validate at least one document is uploaded
            const documentUploads = $('.attachment-file').filter(function() {
                return $(this).val() !== '';
            });
            
            if (documentUploads.length === 0) {
                toastr.warning('Please upload at least one required document');
                $('#headingAttachments').addClass('border-danger');
                $('#collapseAttachments').collapse('show');
                return false;
            }
            
            $.ajax({
                url: $(form).attr('action'),
                type: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                dataType: 'json',
                beforeSend: function() {
                    $('button[type="submit"]').prop('disabled', true)
                        .html('<i class="fas fa-spinner fa-spin me-2"></i> Processing Admission...');
                },
                success: function(response) {
                    if (response.success) {
                        toastr.success(response.msg);
                        if (response.pdf_url) {
                            window.open(response.pdf_url, '_blank');
                        }
                        setTimeout(function() {
                            window.location.href = '<?= base_url('admin/students') ?>';
                        }, 1500);
                    } else {
                        toastr.error(response.msg);
                        $('button[type="submit"]').prop('disabled', false)
                            .html('<i class="fas fa-save me-2"></i> Submit Admission');
                    }
                },
                error: function(xhr) {
                    try {
                        const response = JSON.parse(xhr.responseText);
                        toastr.error(response.message || 'An error occurred. Please try again.');
                    } catch (e) {
                        toastr.error('An error occurred. Please try again.');
                    }
                    $('button[type="submit"]').prop('disabled', false)
                        .html('<i class="fas fa-save me-2"></i> Submit Admission');
                }
            });
        }
    });
});
</script>