<!-- JS Scripts -->
<script src="<?= base_url('resource/adminlte/plugins/jQuery/jQuery-2.1.4.min.js') ?>"></script>
<script src="<?= base_url('resource/adminlte/plugins/jQueryUI/jquery-ui.min.js') ?>"></script>
<script src="<?= base_url('resource/adminlte/bootstrap/js/bootstrap.min.js') ?>"></script>
<script src="<?= base_url('resource/arttemplate/template-native.js') ?>"></script>
<script src="<?= base_url('resource/artdialog/dialog-plus-min.js') ?>"></script>
<script src="<?= base_url('resource/js/jquery.cookie.js') ?>"></script>
<script src="<?= base_url('resource/js/jquery.form.js') ?>"></script>
<script src="<?= base_url('resource/js/bootbox.js') ?>"></script>
<script src="<?= base_url('resource/js/jquery.validate.min.js') ?>"></script>
<script src="<?= base_url('resource/toastr/toastr.min.js') ?>"></script>
<script src="<?= base_url('resource/adminlte/plugins/fastclick/fastclick.min.js') ?>"></script>
<script src="<?= base_url('resource/autosize/autosize.min.js') ?>"></script>
<script src="<?= base_url('resource/momentjs/moment.min.js') ?>"></script>
<script src="<?= base_url('resource/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js') ?>"></script>
<script src="<?= base_url('resource/adminlte/plugins/select2/select2.full.min.js') ?>"></script>
<script src="<?= base_url('resource/adminlte/plugins/fullcalendar/fullcalendar.min.js') ?>"></script>
<script src="<?= base_url('resource/adminlte/plugins/fullcalendar/lang-all.js') ?>"></script>
<script src="<?= base_url('resource/adminlte/plugins/datatables/jquery.dataTables.min.js') ?>"></script>
<script src="<?= base_url('resource/adminlte/plugins/datatables/dataTables.bootstrap.min.js') ?>"></script>
<script src="<?= base_url('resource/adminlte/plugins/slimScroll/jquery.slimscroll.min.js') ?>"></script>
<script src="<?= base_url('resource/adminlte/dist/js/app.min.js') ?>"></script>
<script src="<?= base_url('resource/js/server.js') ?>"></script>
